import os

MQTT_BROKER = os.environ['MQTT_BROKER']
MQTT_PORT = 1883
MQTT_USERNAME = os.environ['MQTT_USERNAME']
MQTT_PASSWORD = os.environ['MQTT_PASSWORD']
DEVICE_IP_ADDRESS = os.environ['DEVICE_IP_ADDRESS']
STATUS_TOPIC = f"iot/{DEVICE_IP_ADDRESS}/status"
SENSOR_TOPIC = f"iot/{DEVICE_IP_ADDRESS}/sensor"
ACTION_TOPIC = f"iot/{DEVICE_IP_ADDRESS}/action"
SETTINGS_UPDATE_TOPIC = f"iot/{DEVICE_IP_ADDRESS}/settings/update"

CAMERA_SOURCE = "usb0"
RESOLUTION = (640, 480)

YOLO_MODEL_PATH = "yolo11n-pose_ncnn_model"
